[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "gcc"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app"