[phases.setup]
nixPkgs = ["python39", "gcc"]

[phases.install]
cmds = ["python -m ensurepip --upgrade", "python -m pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app"